spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/manager?user=root&password=123456&useUnicode=true
  jpa:
    show-sql: true
server:
  context-path: /manager
  port: 8081
swagger:
  groupName: manger
  basePackage: com.jyj.manager.controller